var lang = {

  //signin
  SESSION_EXIT:["세션이 만료되었습니다. 다시 로그인 하여 주십시오.", "Your session has expired. Please log in again.", "会话已过期 请重新登录", "Phiên đã hết hạn. Vui lòng đăng nhập lại."],
  LOGIN_LANG1: ['당신의 디지털 라이프', 'Your Digital Life','你的数字生活',  'あなたのデジタルライフ'],
  LOGIN_LANG2: [
    '비밀번호는 8자 이상, 하나 이상의 숫자 및 대문자와 특수 문자를 포함하여야 합니다.\n인증번호 전송은 서버사정에 따라 5~10초 정도 소요됩니다.',
    'The password must be 8 or more characters, one of the upper and the special character characters and and should be characters.\nAuthentication number transfer takes 5 ~ 10 seconds depending on the server.',
    '密码必须是8个或更多字符，上部字符和特殊字符之一，并且应该是字符。 \n根据服务器的不同，身份验证号码传输需要5到10秒',
    'Mật khẩu phải chứa ít nhất 8 ký tự, ít nhất một số, chữ in hoa và ký tự đặc biệt. \ NTransfer của số xác thực mất 5 ~ 10 giây tùy theo điều kiện máy chủ.'
  ],
  LOGIN_LANG: [
    '인증번호 전송은 서버사정에 따라 5~10초 정도 소요됩니다.',
    'Authentication number transfer takes 5 ~ 10 seconds depending on the server.',
    '根据服务器的不同，身份验证号码传输需要5到10秒',
    'Gửi số xác thực mất khoảng 5 ~ 10 giây tùy theo tình hình máy chủ.'
  ],
  LOGIN_LANG3: ["회원가입", "SIGN UP", "报名", "Trở thành thành viên"],
  LOGIN_LANG4: ["비밀번호 찾기", "Forgot your password", "查找密码", "Tìm mật khẩu"],
  LOGIN_LANG5:  ["로그인하기", "LOGIN", "登录", "Đăng nhập"],
  LOGIN_LANG6: ["이미 로그인 되어있습니다. 메인 페이지로 이동합니다.", "You are already signed in. Go to the main page.", "您已经登录。 转到主页面。", "Bạn đã đăng nhập. Tới trang chính."],
  LOGIN_LANG7: ["중복로그인이 감지되었습니다.", "Duplicate login detected.", "检测到重复登录。", "Phát hiện đăng nhập trùng lặp."],
  LOGIN_LANG8: ["로그인을 하였으나 지갑 주소 생성에 실패했습니다. 관리자에게 문의하세요.",
  "Signed in but failed to create wallet address. Please contact your administrator.",
  "已登录但未能创建钱包地址。 请联系您的管理员。",
  "Tôi đã đăng nhập nhưng việc tạo địa chỉ ví không thành công. Vui lòng liên hệ với quản trị viên của bạn."
],
IMAGE_FILE_UPLOAD_VALID1: ["jpg, png, gif 확장자만 업로드 가능합니다.", "Only jpg, png, gif extensions can be uploaded.","只能上传jpg, png, gif格式的文件","Chỉ có thể tải lên các phần mở rộng jpg, png, gif."],
OTP_CHANGING_VALID1: ["주민등록증 스캔 파일을 선택하여 주십시오.", "Please select a scanned file of your resident registration card.","请选择身份证扫描文件","Vui lòng chọn File Scan Thẻ  Chứng minh nhân dân "],
  OTP_CHANGING_VALID2: ["주민등록증을 들고 찍은 사진 파일을 선택하여 주십시오.", "Please select a picture file with your resident registration card.","请选择拿着身份证拍的照片文件","Vui lòng chọn tệp hình ảnh  có trong thẻ chứng minh nhân dân "],
OTP_CONFIRM_FAIL1: ["OTP코드가 올바르지 않습니다. 다시 시도하여 주십시오.", "The OTP code is incorrect. Please try again.","OTP代码不正确  请重试","Mã OTP không chính xác. Vui lòng thử lại."],
OTP_CONFIRM_FAIL2: ["OTP코드 입력시간이 초과하였습니다. 바뀐 코드를 입력하십시오.", "OTP code input time exceeded. Please enter the changed code.","输入OTP代码已超时   请输入改变的代码","Đã vượt quá thời gian nhập mã OTP. Vui lòng nhập mã đã thay đổi."],
OTP_CONFIRM_SUCCESS: ["OTP 등록에 성공했습니다.", "OTP registration succeeded.","成功注册OTP","Đăng ký OTP đã thành công."],
LOGIN_OTP: ['OTP코드를 입력하세요.', 'Enter the OTP code.',"请输入OTP代码","Vui lòng nhập mã OTP."],
OTP_LOGIN_FAIL1: ["OTP정보가 등록되어 있지 않습니다. 관리자에게 문의 바랍니다.", "OTP information is missing. Please contact your administrator.","无注册OTP信息   请咨询管理员","Thông tin OTP không được đăng ký. Vui lòng liên hệ với quản trị viên để được tư vấn "],
MYPAGE_INFO13:["OTP 인증","OTP authentication","OTP认证","Xác thực OTP"],

LOGIN_LANG9: ["보안 설정 중 입니다. 잠시만 기다려주십시오.", "Security setting is in progress. Please wait a moment.", "安全设置正在进行中。 请稍等。", "Thiết lập bảo mật Xin vui lòng chờ"],
LOGIN_LANG10: ["데이터 처리 중입니다 5~10초 소요될 예정입니다.", "Data is being processed It will take 5-10 seconds.", "正在處理數據 这将需要5-10秒。", "Việc xử lý dữ liệu dự kiến ​​sẽ mất 5-10 giây."],
LOGIN_LANG11: ["이 화면이 지속되면 페이지를 새로고침(F5) 해주세요", "If this screen persists, please refresh the page (F5).", "如果此屏幕仍然存在，請刷新頁面（F5）。", "Nếu màn hình này vẫn còn, vui lòng làm mới trang (F5)."],
LOGOUT_LANG1: ["로그아웃 되었습니다.", "You have been signed out.", "你已经退出。", "Bạn đã đăng xuất."],
LOGIN_VALID1: ["아이디를 입력하십시오.", "Please enter your ID.", "輸入您的用戶名。", "Vui lòng nhập ID của bạn."],
LOGIN_VALID2: ["비밀번호를 입력하십시오.", "Please enter your password.", "輸入密碼。", "Vui lòng nhập mật khẩu."],
LOGIN_FAILED1: ["인증을 완료하십시오.", "Please complete the verification.", "請填寫驗證。", "Hoàn thành chứng nhận."],
LOGIN_FAILED2: ["정보가 일치하지 않습니다.", "The information does not match.", "該信息不匹配。", "Thông tin không khớp."],
LOGIN_FAILED3: ["이미 다른 장비에서 로그인 중입니다.", "You are already signed in on another device.", "您已在其他设备上登录。", "Bạn đã đăng nhập từ một thiết bị khác."],
LOGIN_FAILED4: ["이미 로그인 된 계정이 있습니다.", "You already have a signed-in account.", "您已拥有登录帐户。", "Tôi đã có một tài khoản đăng nhập."],
LOGIN_FAILED5: ["OTP로그인을 진행 하세요.", "Proceed to OTP Login", "继续进行OTP登录", "OTPログインを進めてください"],
SIGNUP_LANG1: ["회원가입하기", "Sign up", "注册", "Tham gia ngay"],
SIGNUP_LANG2: ["첫 방문을 환영합니다.", "Welcome to our first visit.", "欢迎来到我们的首次访问。", "Chào mừng chuyến thăm đầu tiên của bạn."],
SIGNUP_VALID1: ["이메일을 입력하십시오.", "Please enter your email.", "请输入你的电子邮件。", "Vui lòng nhập email của bạn."],
SIGNUP_VALID2: ["비밀번호 확인을 입력하십시오.", "Please enter your password verification.", "请输入您的密码验证。", "Nhập mật khẩu xác nhận."],
SIGNUP_VALID3: ["비밀번호가 맞지 않습니다.", "The password is incorrect.", "密碼不正確。", "Mật khẩu không đúng"],
SIGNUP_VALID4: ["인증번호 입니다.", "Authorization number.", "授权号码。", "Số xác thực."],
SIGNUP_VALID5: ["정상적으로 가입되었습니다.", "You have successfully signed up.", "您已成功注册。", "Bạn đã tham gia thành công"],
SIGNUP_VALID6: ["인증메일 발송에 실패했습니다. 관리자에게 문의하세요.",
"Failed to send verification mail. Please contact your administrator.",
"无法发送验证邮件。 请联系您的管理员。",
"Không thể gửi email xác minh. Vui lòng liên hệ với quản trị viên của bạn."
],
SIGNUP_VALID7: ["아이디가 중복되었습니다.", "Duplicate ID.", "重复的ID。", "ID được nhân đôi."],
SIGNUP_VALID8: ["이메일이 중복되었습니다.", "Duplicate email", "重复的电子邮件", "Email trùng lặp"],
SIGNUP_VALID9: [
  "비밀번호에는 적어도 하나 이상의 대문자와 소문자, 숫자, 특수문자를 포함해야 합니다.", "Passwords must include at least one uppercase letter, lowercase letters, numbers, and special characters.",
  "密码必须至少包含一个大写字母，小写字母，数字和特殊字符。", "Mật khẩu phải chứa ít nhất một chữ hoa và chữ thường, số và ký tự đặc biệt."
],
SIGNUP_VALID10: ["이름을 입력하십시오.", "Please enter your name.", "请输入您的密码验证。", "Vui lòng nhập tên."],
SIGNUP_VALID11: ["문자에 공백이 포함되어있습니다.다시 입력해주세요", "The text contains spaces. Please re-enter.", "文字包含空格。请重新输入。", "Nhân vật chứa một khoảng trắng, vui lòng thử lại"],
SIGNUP_VALID12: ["중복 된 전화 번호", "Duplicate phone number","重复的电话号","Số điện thoại trùng lặp"],
SIGNUP_VALID13: ["탈퇴한회원아이디로는 가입이 불가능합니다.", "You can not join with the member ID you left.","您無法加入您留下的會員ID。","Bạn không thể tham gia với ID thành viên đã rút."],
EMAIL_CONFIRM_VALID1: ["이메일 인증번호를 입력하십시오.", "Please enter your email verification number.", "请输入您的电子邮件验证码。", "Vui lòng nhập số xác minh email của bạn."],
EMAIL_CONFIRM_VALID2: ["인증번호를 재전송하시겠습니까?", "Are you sure you want to retry the authorization number?", "号码吗？", "Bạn có muốn gửi lại số xác minh?"],

EMAIL_CONFIRM_RESEND: ["인증번호 재전송이 완료되었습니다. ", "Verification number retransmission is completed.", "验证号码重传完成。", "Gửi lại số xác minh là xong."],
EMAIL_CONFIRM_SUCCESS: ["인증이 완료되었습니다.", "Verification is complete.", "驗證已完成。", "Chứng nhận hoàn thành."],
EMAIL_CONFIRM_FAIL: ["정보가 일치하지 않습니다.", "The information does not match.", "該信息不匹配。", "Thông tin không khớp."],
EMAIL_CONFIRM_LANG1: [
  '인증번호 전송은 서버사정에 따라 5~10초 정도 소요됩니다.',
  'Authentication number transfer takes 5 ~ 10 seconds depending on the server.',
  '根据服务器的不同，身份验证号码传输需要5到10秒',
  'Gửi số xác thực mất khoảng 5 ~ 10 giây tùy theo tình hình máy chủ.'
],
EMAIL_CONFIRM_LANG2: ["인증번호가 도착하면 확인을 눌러주시고, ", "When the authentication number arrives, please click OK,", "当验证码到达时，请点击确定，",  "Nhấn OK khi số xác minh đến,"],
EMAIL_CONFIRM_LANG3: ["인증번호가 도착하지 않을 경우 재전송 버튼을 눌러주세요", "If you do not receive your verification number please press the Resend button", "如果您未收到验证码，请按“重新发送”按钮", "Nếu số xác minh không đến, nhấn nút Gửi lại."],
EMAIL_CONFIRM_LANG4: ["이메일 인증번호 확인", "Check your email verification number", "检查您的电子邮件验证码",  "Xác nhận số xác minh email"],
EMAIL_CONFIRM_LANG5: ["재전송", "re-send", "重发", "Gửi lại"],
SYSTEM_ERROR1: ["시스템 에러가 발생했습니다.", "A system error has occurred.", "发生系统错误。", "Một lỗi hệ thống đã xảy ra."],
SYSTEM_ERROR2: ["잘못된 접근입니다.", "Invalid access", "无效的访问", "Cách tiếp cận không hợp lệ"],
SESSION_EXIT: ["세션이 만료되었습니다. 다시 시도해 주십시오.", "Your session has expired. Please try again.", "您的会话已过期。 请再试一次。", "Phiên đã hết hạn. Vui lòng thử lại."],
SESSION_EXIT2: ["세션이 만료되었습니다. 다시 로그인하여 주십시오.", "Your session has expired. Please log in again.", "您的会话已过期。 请重新登录。", "Phiên hết hạn. Vui lòng đăng nhập lại."],
MAIN_LANG1: ["최근접속일", "Recently accessed", "最近访问过", "Kết nối lần cuối"],
MAIN_LANG2: ["받기", "Receive", "存", "Nhận"],
MAIN_LANG3: ["보내기", "Send", "提款", "Gửi"],
MAIN_LANG4: ["거래내역보기", "View history", "查看交易历史", "Xem giao dịch"],

MAIN_LANG5: ["계좌", "Account", "帐号", "Tài khoản"],
MAIN_LANG6: ["님의 계좌 미생성", "account not created", "未创建帐户", "Chưa tạo tài khoản cho"],
MAIN_LANG7: ["아래의 생성버튼을 클릭하여 새로운 계좌를 만드세요", "Account", "单击下面的“创建”按钮以创建新帐户", "Nhấp vào nút Tạo bên dưới để tạo tài khoản mới."],
MAIN_LANG8: ["님의", " for", " 小号", " 'S"],
MAIN_LANG9: ["님의 ETH계좌 미생성", "ETH account not created", "未创建ETH帐户", "Chưa tạo tài khoản ETH cho"],
PASS_CHANGE_POP_LANG1: ["비밀번호 변경", "Change Password", "更改密码", "Thay đổi mật khẩu"],
PASS_CHANGE_POP_LANG2: [
  "비밀번호의 주기적인 변경은 회원님의 정보를 안전하게 지킬 수 있는 가장 간단하고 빠른 방법입니다.",
  "Changing your password regularly is the simplest and quickest way to keep your information safe.",
  "定期更改密码是保证信息安全的最简单最快捷的方式。",
  "Thay đổi mật khẩu định kỳ là cách đơn giản nhất và nhanh nhất để bảo mật thông tin của bạn."
],
//PASS_CHANGE_POP_LANG3: ["비밀번호 찾기", "Find your password", "查找密码", "パスワードを忘れた"],
PASS_CHANGE_POP_VALID1: ["기존 비밀번호를 입력하세요.", "Please enter your existing password.", "请输入您现有的密码。", "Vui lòng nhập mật khẩu cũ của bạn."],
PASS_CHANGE_POP_VALID2: ["신규 비밀번호를 입력하세요.", "Please enter a new password.", "请输入新密码。", "Vui lòng nhập một mật khẩu mới."],
PASS_CHANGE_POP_VALID3: ["신규 비밀번호를 다시 입력하세요.", "Please re-enter your new password.", "请重新输入您的新密码。", "Vui lòng nhập lại mật khẩu mới."],
PASS_CHANGE_POP_VALID4: [
  "신규비밀번호 확인이 신규비밀번호와 다릅니다.", "New password verification is different from new password.",
  "新密码验证与新密码不同。", "Kiểm tra mật khẩu mới khác với mật khẩu mới."],
  CHANGE_PASSWORD_FAIL1: [
    "신규 비밀번호는 기존 비밀번호와 달라야 합니다.", "Your new password must be different from your existing password.",
    "您的新密码必须与您现有的密码不同。", "Mật khẩu mới phải khác với mật khẩu hiện có."],
    SETTING_VALID1: [
      "정말로 계정을 삭제하시겠습니까? 취소할 수 없습니다.", "Are you sure you want to delete your account? It can not be canceled.",
      "您确定要删除您的帐户吗？ 它不能被取消。", "Bạn có thực sự muốn xóa tài khoản của bạn? Không thể hủy bỏ."],
      SETTING_LANG1: ["개인설정", "Personal settings", "个人设置", "Cá nhân hóa"],
      SETTING_LANG2: ["비밀번호 변경", "Change Password", "更改密码", "Thay đổi mật khẩu"],
      SETTING_LANG3: ["사용자의 비밀번호를 변경합니다.", "Change the user's password.", "更改用户的密码。", "Thay đổi mật khẩu người dùng."],
      SETTING_LANG4: ["계정삭제", "delete account", "删除帐户", "Xóa tài khoản"],
      SETTING_LANG5: ['삭제', 'delete', '删除', 'Xóa'],
      SETTING_LANG6: ["서버에 있는 모바일 계정정보를 삭제합니다.", "Delete the mobile account information on the server.", "删除服务器上的移动帐户信息。", "Xóa thông tin tài khoản di động khỏi máy chủ."],
      SETTING_LANG7: ["친구설정", "Set up your friends", "建立你的朋友", "Cài đặt bạn bè"],
      SETTING_LANG8: ["전화번호부 이름표시", "Display phone book name", "显示电话簿名称", "Hiển thị tên danh bạ điện thoại"],
      SETTING_LANG9: ["표시중", "Displaying", "显示", "Đang hiển thị"],
      SETTING_LANG10: ["친구이름을 전화번호부에서 사용하는 이름으로 표시합니다.", "Show your friend's name as the name you use in your phone book.", "将您的朋友的姓名显示为您在电话簿中使用的姓名。", "Hiển thị tên của bạn bè như tên được sử dụng trong danh bạ điện thoại."],
      SETTING_LANG11: ["서비스정보", "Service Information", "服务信息", "Thông tin dịch vụ"],
      SETTING_LANG12: ["프로그램정보", "Program Information", "节目信息", "Thông tin chương trình"],
      SETTING_LANG13: ["변경", "change", "变化", "Thay đổi"],

      SETTING_LANG14: ["언어 변경", "Change language", "改变语言", "Thay đổi ngôn ngữ"],
      SETTING_LANG15: ["다른언어로 변경합니다.", "Change to another language.", "换到另一种语言。", "Thay đổi ngôn ngữ khác."],
      WORK_COMPLETE: ["정상적으로 처리되었습니다.", "Successfully processed.", "成功处理。", "Chế biến thành công"],

      FIND_PASSWORD_LANG1: ['비밀번호 찾기', "Forgot your password", "查找密码", "Tìm mật khẩu"],
      FIND_PASSWORD_LANG2: ["비밀번호는 회원가입시 등록된 e-mail을 입력하여주세요.", "Please enter your e-mail address when registering for membership.", "请在注册时输入您的电子邮件地址。", "Vui lòng nhập địa chỉ e-mail của bạn khi đăng ký."],
      FIND_PASSWORD_LANG3: ["검색하신 비밀번호는 메일로 발송됩니다.", "The password you searched will be sent by e-mail.", "您搜索的密码将通过电子邮件发送。", "Mật khẩu bạn đã lấy sẽ được gửi qua email."],

      FIND_PASSWORD_FAIL1: ["존재하지 않는 이메일입니다.", "Email does not exist", "电子邮件不存在", "Email này không tồn tại."],
      FIND_PASSWORD_FAIL2: ["이미 탈퇴한 회원입니다.", "I am a member who has already left.", "我是已经离开的会员。", "Bạn đã là thành viên."],
      FIND_PASSWORD_FAIL3: ["메일 발송에 실패했습니다. 관리자에게 문의하세요.", "Failed to send mail. Please contact your administrator.", "メール送信に失敗しました。管理者にお問い合わせください。", "Không thể gửi thư Vui lòng liên hệ với quản trị viên của bạn."],
      FIND_PASSWORD_SUBJECT: ["비밀번호 찾기 메일입니다.", "It is a password retrieval mail.", "这是一个密码检索邮件。", "Quên tin nhắn mật khẩu."],
      USER_DELETE_FAIL1: ["코인 잔액이 남아 있습니다.", "Coin Quantity remaining.", "剩余的硬币余额。", "Số dư tiền còn lại."],

      SEND_PROCESS_VALID1: ["코인주소를 입력하세요.", "Please enter your coin address.", "请输入您的硬币地址。", "コVui lòng nhập một địa chỉ tiền xu."],
      SEND_PROCESS_VALID2: ["코인수량 을 입력하세요.", "Please enter coin quantity.", "请输入硬币数量！。", "Vui lòng nhập số lượng tiền."],

      SEND_PROCESS_FAIL1: ["잔액이 부족합니다.", "There is not enough balance or fee.", "缺乏平衡。", "Bạn đã hết cân bằng."],
      SEND_PROCESS_FAIL2: ["수수료 혹은 ETH가 부족합니다.", "There is not enough balance or fee.", "金额有误。", "Phí không đủ hoặc ETH"],
      SEND_PROCESS_FAIL3: ['존재하지 않는 주소입니다.', 'The address does not exist.', '一個不存在的地址。', 'Địa chỉ này không tồn tại.'],
      SEND_PROCESS_FAIL4: ["비밀번호가 잘못되었습니다!", "Your password for is incorrect!","密码无效！","Mật khẩu không hợp lệ!"],
      SEND_PROCESS_FAIL5: ["거래가 정지된 계정입니다.", "Your account has been suspended.","您的帐户已被暂停。","Tài khoản này đã bị đình chỉ."],
      SEND_PROCESS_FAIL6: ["잘못된 계좌 혹은 KCP지갑에 등록되어있지 않은 계좌입니다.", "It is an account that is not registered in the wrong account or HGC wallet.","这是一个未在错误的帐户或HGC钱包中注册的帐户","Tài khoản này không được đăng ký trong tài khoản hoặc ví KCP sai."],
      SEND_PROCESS_SUCCESS: ["성공적으로 이체하였습니다.", "Successfully transferred.", "成功?移。", "Bạn đã chuyển thành công."],

      WALLET_LANG1: ["주소복사", "Copy the address", "复制地址", "Sao chép địa chỉ"],
      WALLET_LANG2: ["출금하기", "Withdraw", "退出", "Rút tiền"],
      WALLET_LANG3: ["거래완료", "Transaction complete", "交易完成", "Giao dịch hoàn tất"],
      WALLET_LANG4: ["거래컨펌중", "Deal concur", "交易一致", "Xác nhận giao dịch"],
      WALLET_LANG5: ["주소가 복사되었습니다.", "Address copied.", "地址复制。", "Địa chỉ đã được sao chép."],
      WALLET_LANG6: ["거래내역.", "Transaction history.", "交易记录", "Lịch sử giao dịch"],
      WALLET_LANG7: ["출금가능 CFT.", "Withdrawable CFT amount", "可提取金额", "Rút tiền CFT có thể."],
      WALLET_LANG8: ["출금주소를 입력하세요.", "Please enter your withdrawal address.", "请输入您的提款地址。", "Vui lòng nhập địa chỉ rút tiền."],
      WALLET_LANG9: ["출금금액을 입력하세요.", "Please enter the withdrawal amount.", "请输入提款金额。", "Vui lòng nhập số tiền rút"],

      WITHDRAW_LANG1: ['전송가능수량', 'Tagie Coin Quantity', '退出金额', 'Số lượng chuyển nhượng'],
      WITHDRAW_LANG2: ['숫자만 입력 가능합니다.', 'Only numbers can be entered.', '只能输入数字。', 'Chỉ có thể nhập số.'],
      WITHDRAW_LANG3: ['자신이 자신에게 보낼 수 없습니다. 로그인된 정보를 확인하세요.', 'I can not send myself to myself. Please check your logged in information.', '我无法把自己献给自己。 请检查您登录的信息。', 'Bạn không thể gửi nó cho chính mình. Vui lòng kiểm tra thông tin đăng nhập.'],

      COMMON_LANG1: ['알림', 'notice', '通知', 'Thông báo'],
      COMMON_LANG2: ['닫기', 'close', '关闭', 'Đóng'],

      MENU_LANG1: ['로그아웃', 'Log out', '退出', 'Đăng xuất'],
      MENU_LANG2: ['설정하기', 'Set up', '设置', 'Thiết lập'],
      MENU_LANG3: ['자산', 'Assets', '资产', 'Tài sản'],
      IMAGE_FILE_UPLOAD_FAIL1: [
          "파일을 올리던 도중 오류가 발생했습니다. 잠시 후 다시 시도하여 주십시오. \n지속적으로 문제 발생 시 시스템 관리자에게 문의 바랍니다.",
          "There was an error uploading the file. Please try again later. \nPlease consult with your system administrator if problems persist."
        ,"上传文件过程中发生故障   请稍后重试\n持续出现问题时，请咨询系统管理员","phát sinh sự cố trong lúc tải tệp lên . Vui lòng thử lại sau.\nVui lòng liên hệ với quản lí hệ thống khi có phát sinh vấn đề liên tục  "],
      DELETE_LANG1: ["계정을 삭제합니다.", "Delete the account.", "删除该帐户。", "Xóa tài khoản của bạn."],
      DELETE_LANG2: ["이메일로 발송된 인증번호 5자리를 입력하여 주십시오.", "Please enter the 5 digits of the verification number sent by e-mail.", "请输入通过电子邮件发送的验证码的5位数字。", "Vui lòng nhập mã xác minh gồm 5 chữ số được gửi qua email."],
      DELETE_LANG3: ["계정 삭제 인증번호 입니다.", "Account deletion authorization number.", "帐户删除授权号码。", "Số ủy quyền xóa tài khoản."],
      DELETE_VALID1: ["인증번호가 올바르지 않습니다.", "The verification number is invalid.", "验证号码无效。", "Số ủy quyền không chính xác."],
OTP_CHANGING_SUCCESS: ["정상적으로 업로드 되었습니다. 운영진이 확인하는데에 1~3일 정도 소요됩니다.", "Uploaded successfully It takes 1 ~ 3 days for the management to check.","已上传   审批需要1~3日    ","Đã được Tải lên thành công.  Thời gian duyệt của quản trị viên là từ 1~3 ngày "],
      FORGOT_PASSWORD_SUCCESS: ["이메일로 비밀번호를 발송했습니다. 이메일을 확인하여 주십시오.", "Your password was sent by email. Please check your email.","通过电子邮箱已发送密码   请确认电子邮箱","Mật khẩu của bạn đã được gửi qua email. Vui lòng kiểm tra email của bạn."],
      FORGOT_PASSWORD_FAIL1: ["입력하신 이메일로 등록된 ID가 존재하지 않습니다.\n이메일 주소를 확인하세요.", "The ID you entered does not exist, please check your email address.","您输入的电子邮箱注册的ID不存在\n请确认电子邮箱地址","ID của bạn đã nhập trong email không tồn tại.\nVui lòng kiểm tra địa chỉ e-mail của bạn."],
      RECOVER2: ["아직 회원이 아니신가요?", "Not yet a member?","还不是会员？","Chưa là thành viên?"],
      RECOVER1: ["이메일을 입력하세요.", "Please enter your email.","请输入您的电子邮件。","Vui lòng nhập email."],
      RECOVER3: ["로그인하러가기", "Go to login","去登录。","Đi đến đăng nhập"],
      RECOVER4: ["비밀번호 찾기", "Forgot your password","找到密码","Tìm mật khẩu"],
      RECOVER5: ["로그인", "Sign in","签到","Đăng nhập"],
      RECOVER6: ["아이디를 입력하세요.", "Please enter your ID.","请输入您的ID。","Vui lòng nhập ID của bạn"],
      RECOVER7: ["비밀번호를 입력하세요.", "Please enter your password correctly.","请正确输入您的密码","Vui lòng nhập mật khẩu."],
      RECOVER8: ["아이디저장", "save ID","保存ID","Lưu ID"],
      RECOVER9: ["자동 로그인", "Auto-Login","自动登录","Đăng nhập tự động"],
      RECOVER10: ["비밀번호를 다시 입력하세요.", "Please re-enter your password.","请重新输入您的密码。","Vui lòng nhập lại mật khẩu của bạn."],
      RECOVER11: ["이름을 입력하세요", "Please enter your name.","请重新输入您的密码。","Vui lòng nhập tên của bạn"],
      RECOVER12: ["OPT초기화 신청", "Request OPT Initialization.","请求OPT初始化","Ứng dụng khởi tạo OPT"],
      RECOVER13: ["전화번호를 입력하세요", "Please enter your phone number","请输入您的电话号码","Vui lòng nhập số điện thoại của bạn"],


      POP1: ["비밀번호 생성", "Generate password","生成密码","Tạo mật khẩu"],
      POP2: ["coin 비밀번호는 변경 & 찾기가 불가능하니 꼭!! 기억해주세요 비밀번호는 숫자,대소문자를 꼭 포함하여야 합니다.", "You can not change your coin password. Remember, passwords must include numbers and upper and lower case letters.","您无法更改您的硬币密码。 请记住，密码必须包含数字和大写和小写字母。","Bạn không thể thay đổi và tìm mật khẩu tiền xu! Xin nhớ rằng mật khẩu của bạn phải chứa số và chữ hoa và chữ thường."],
      POP3: ["비밀번호 생성", "Create password","创建密码","Tạo mật khẩu"],
      POP4: ["비밀번호가 잘못되었습니다!", "Your password for is incorrect!","密码无效！","Mật khẩu không hợp lệ!"],
      POP5: ["시스템 오류로 코인을 보내지 못했습니다!", "Sending coin failed due to system error!","由于系统错误，无法发送硬币！","Coin không được gửi do lỗi hệ thống!"],
      POP6: ["기간이 만료되었습니다. 다시 로그인하십시오.", "Your session has expired. Please login again.","期限已过期。 请再次登录。","Thời hạn đã hết hạn. Vui lòng đăng nhập lại."],
      POP7: ["COIN 전송 성공하였습니다 트랜젝션까지 3~5분 정도 소요될 수있습니다.", "COIN transmission succeeded Transactions can take 3-5 minutes","COIN传输成功 交易可能需要3-5分钟","Chuyển COIN thành công. Có thể mất 3 ~ 5 phút để hoàn tất giao dịch."],
      POP8: ["귀하의 비밀번호와 확인 비밀번호가 일치하지 않습니다!", "Your password and confirm password does not match!","您的密码和确认密码不符！","Mật khẩu và mật khẩu xác nhận của bạn không khớp!"],
      POP9: ["비밀번호를 올바르게 입력해 주세요", "Please enter your password correctly","请正确输入您的密码","Vui lòng nhập mật khẩu hợp lệ"],


      LOGIN_LANG0: ["지갑 생성에 성공하셨습니다..", "You have successfully created wallet",
      "已登录但未能创建钱包地址。 请联系您的管理员。",
      "Bạn đã tạo thành công ví của bạn."],
      HYGENMAIN1: ["HGCCOIN 생성하기","Creating HGCCOIN","创建HGCCOIN","HGCCOIN生成する"],
      HYGENMAIN2: ["HGCCOIN은 비밀번호가 필요합니다.","HGCCOIN requires a password.","HGCCOIN需要密码。","ETH yêu cầu mật khẩu.。"],
      HYGENMAIN3: ["1주일","1 week","一周","1 tuần"],
      HYGENMAIN4: ["1개월","1 month","1个月","1 tháng"],
      HYGENMAIN5: ["3개월","3 month","3个月","3 tháng"],
      HYGENMAIN6: ["6개월","6 month","6个月","6 tháng"],
      HYGENMAIN7: ["잔액","Your Balance","您的余额","Số dư"],
      HYGENMAIN8: ["환영합니다.","Hello","欢迎。","Chào mừng bạn"],
      HYGENMAIN9: ["공지사항.","Notice","通知","Thông báo."],
      HYGENMAIN10: ["마지막 접속일","Last access date","上次访问日期","Lần cuối trực tuyến"],
      HYGENMAIN11: ["입/출금","Input / withdrawal","输入/退出","Vào / ra"],
      HYGENMAIN12: ["입금하기","Deposit","存","Gửi tiền"],
      HYGENMAIN13: ["QR주소보기","View QR address","查看QR地址","Xem địa chỉ QR"],
      HYGENMAIN14: ["주소복사하기","Copy the address","复制地址","Sao chép địa chỉ"],
      HYGENMAIN15: ["ETH 생성하기","Creating ETH","创建ETH","Tạo ETH"],
      HYGENMAIN16: ["ETH은 비밀번호가 필요합니다.","ETH requires a password.","ETH需要密码。","ETH yêu cầu mật khẩu."],

      DAY1: ["월요일","Monday","星期一","Thứ hai"],
      DAY2: ["화요일","Tuesday","星期二","Thứ ba"],
      DAY3: ["수요일","Wednesday","星期三","Thứ tư"],
      DAY4: ["목요일","Thursday","星期四","Thứ năm"],
      DAY5: ["금요일","Friday","星期五","Thứ sáu"],
      DAY6: ["토요일","Saturday","星期六","Thứ bảy"],
      DAY7: ["일요일","Sunday","星期天","Chủ nhật"],
      DAY8: ["년","year","年","Năm"],
      DAY9: ["월","month","月","Tháng"],
      DAY10: ["일","day","天","Ngày"],
      DAY12: ["거래컨펌중","Pending..","批准交易","Xác nhận giao dịch"],
      DAY13: ["거래완료","Transaction complete","交易完成","Giao dịch hoàn tất"],
      DAY14: ["거래실패","Transaction failed","交易失败","Giao dịch thất bại"],
      BASICINFO1: ['기본정보', 'BasicInfoMation', '基本信息', 'Thông tin cơ bản'],
      BASICINFO2: ['아이디', 'ID', '用户名', 'ID'],
      BASICINFO3: ['성명', 'Name', '声明', 'Tuyên bố'],
      BASICINFO4: ['이메일', 'Email', '电子邮件', 'Email'],
      BASICINFO5: ['전화번호', 'Phone', '电话号码', 'Số điện thoại'],
      BASICINFO6: ['OTP 인증', 'OTP authentication', 'OTP认证', 'Xác thực OTP'],
      BASICINFO7: ['인증 미완료', 'Incomplete certification', '不完整的认证', 'Không được chứng nhận'],
      BASICINFO8: ['인증하기', 'Authenticate', '认证', 'Xác thực'],
      BASICINFO10: ['등록하기', 'registration', '注册', 'Đăng ký'],
      BASICINFO9: ['인증완료', 'Verification completed', '认证', 'Chứng nhận hoàn thành'],
      BASICINF11: ['외부 출금계좌 등록(ETH)', 'External withdrawal account registration (ETH)', '外部提款账户注册（ETH）', 'Đăng ký tài khoản rút tiền bên ngoài (ETH)'],
      BASICINF12: ['출금계좌 등록성공', 'Successful registration withdrawal account', '成功注册部提款账户', 'Rút tiền đăng ký tài khoản thành công'],
      BASICINF13: ['계좌번호가 잘못되었습니다.', 'Invalid account number.', '帐号无效。', 'Số tài khoản không hợp lệ.'],
      WALLET1: ['메모', 'MEMO', '认证', 'Ghi nhớ'],

      REVIE1:['확    인','Confirm','確    認','Được rồi'],
      REVIE2:['전체동의','Entire Agreement','完整協議','Tất cả đồng ý'],
      REVIE3:['이용약관 동의','Accept terms and conditions','接受條款和條件','Điều khoản và điều kiện Đồng ý'],
      REVIE4:['개인정보처리방침 동의','Consent to Personal Information Processing Policy','同意個人信息處理政策','Chính sách bảo mật Đồng ý'],
      REVIE5:['보기','look','看','Xem'],
      REVIE6:['다음','Next','下','Tiếp theo'],
      REVIE7:['약관동의','Accept terms','接受條款','Hiệp định'],
      REVIE8:['이용약관','Terms of service','條款和條件','Điều khoản sử dụng'],
      REVIE9:['수신동의','Acceptance','選擇','Nhận thỏa thuận'],
      REVIE10:['동의하지않습니다.','I do not agree.','我不同意。','Tôi không đồng ý'],
      REVIE11:['Push 수신동의','Push reception agreement','推送接收協議','Thỏa thuận đẩy nhận'],
      REVIE12:['동의합니다.','I agree.','我同意。','Tôi đồng ý'],
      REVIE13:['마케팅 수신동의','Marketing acceptance','營銷驗收','Đồng ý tiếp thị'],
      REVIE14:['동의하시면, 이벤트 알림을 실시간으로 받아보실 수 있습니다.','If you agree, you can receive event notifications in real time.','如果您同意，您可以實時接收事件通知。','Nếu bạn đồng ý, bạn sẽ nhận được thông báo sự kiện trong thời gian thực.'],
      REVIE15:['항목','Item','項目','Mục'],
      REVIE16:['모바일 앱 알림동의','Mobile app notification acceptance','移動應用通知接受','Đồng ý thông báo ứng dụng di động'],
      REVIE17:['이용목적','purpose of use','使用目的','Mục đích sử dụng'],
      REVIE18:['이벤트등의 다양한 소식 안내','Various events such as events','各種活動，如活動','Hướng dẫn tin tức khác nhau như các sự kiện'],
      REVIE19:['내 정보','My Info','我的信息','Thông tin của tôi'],

      REVIE20:['보안설정','Security settings','安全設置','Cài đặt bảo mật'],
      REVIE21:['설정','Set','設置','Thiết lập'],
      REVIE22: ["주소록","address book","地址簿","Sổ địa chỉ"],
      REVIE23: ["주소를 잘못 입력하실 경우에는 정상적인 입금 처리가 되지 않으며,\n고객의 실수로 사라진 코인은 복구되지 않습니다.","If you make a mistake, we will not be able to process your deposit correctly, \n You will not be able to recover your lost coin.","如果您犯了错误，我们将无法正确处理您的存款，\n 您将无法收回丢失的硬币。","Nếu bạn nhập sai địa chỉ, chúng tôi sẽ không thể xử lý khoản tiền gửi của bạn. \ NCoins bị mất do nhầm lẫn sẽ không được phục hồi."],
      REVIE24:['회원가입시 작성한 전화번호로 인증번호가 발송됩니다. 그리고 sms보안은 입출금시 사용됩니다.','An authentication number will be sent to the phone number created at the time of membership registration. And sms security is used when depositing and withdrawing money.','身份驗證號碼將發送到會員註冊時創建的電話號碼。 存款和取款時使用短信安全。','Số xác minh sẽ được gửi đến số điện thoại được tạo trong quá trình đăng ký. Và bảo mật sms được sử dụng để gửi và rút tiền.'],
      REVIE25:['2차 비밀번호','Second password','第二個密碼','2次パスワード'],
      REVIE26:['2차 비밀번호 보안은 입출금, 로그인시 사용됩니다.','SECURITY is used to deposit, withdraw and login.','安全保障安全用於存款，取款和登錄。','2次パスワードのセキュリティは入出金、ログイン時に使用されます。'],
      REVIE27:['2차 비밀번호 설정','Setting a secondary password','設置二級密碼','2次パスワードの設定'],
      REVIE28:['내역','History','歷史','Sự cố'],
      REVIE29:['거래금액','Transaction amount','交易金額','Số tiền giao dịch'],
      REVIE30:['거래상황','Transaction situation','交易情況','Tình trạng giao dịch'],
      REVIE31:['거래구분','Transaction classification','交易分類','Giao dịch'],
      REVIE32:['거래시각','Trading time','交易時間','Thời gian giao dịch'],
      REVIE33:['거래중','In transit','在途中','Giao dịch'],
      REVIE34:['입금계좌','Deposit account','存款賬戶','Tài khoản tiền gửi'],
      REVIE35:['비밀번호가 기억나지 않으신다면,','If you do not remember your password,','如果您忘記密碼，','Nếu bạn không nhớ mật khẩu của mình,'],
      REVIE36:['고객센터로 문의바랍니다.','Please contact customer center.','請聯繫客戶中心。','Vui lòng liên hệ với dịch vụ khách hàng.'],
      REVIE37:['재배치','Relocation','搬遷','Di dời'],
      REVIE38:['리스트 보기','List View','列表視圖','Xem danh sách'],
      REVIE39:['정보수정','Changing information','編輯信息','Chỉnh sửa thông tin'],
      REVIE40:['회원가입할때 입력하신 메일로','By the email you entered when signing up','通過您在註冊時輸入的電子郵件','Để email bạn đã nhập khi đăng ký'],
      REVIE41:['인증번호가발송되었습니다.','The authorization number has been sent.','您的驗證碼已發送。','Một số xác minh đã được gửi.'],
      REVIE42:['문의하기','Contact us','聯繫我們','Liên lạc với chúng tôi'],
      REVIE43:['문의내역확인','Check your inquiry history','查看您的查詢記錄','Xác nhận điều tra'],
      REVIE44:['일반문의','General inquiries','一般查詢','Điều tra chung'],
      REVIE45:['계정문의','Account inquiry','帳戶查詢','Yêu cầu tài khoản'],
      REVIE46:['답변 받을 이메일 주소','Email address to respond to','要回复的電子郵件地址','回答受信するメールアドレス'],
      REVIE47:['첨부파일 추가','Add attachment','添加附件','添付ファイルの追加'],
      REVIE48:['동의하신 내용에 대한 원인파악 및 원할한 상담을 위하여 이메일, 휴대폰번호를 수집합니다. 수집된 개인정보는 개인정보의 수집 및 이용목적이 달성되면 관련 법령 또는 회사 내부 방침에 의해 보존할 필요가 는 경우를 제외하고 지체없이 파기합니다. \n 더 자세한 내용은 \n개인정보처리방침 \n을 참고하시기바랍니다.','We collect e-mails and mobile phone numbers for the purpose of understanding the cause of the agreement and for consultation. Once the purpose of collecting and using personal information is achieved, we will destroy the collected personal information without delay, except when it is necessary to preserve it according to related laws or company internal policies. \n For more information, please refer to \n Privacy Policy \n.',
      '我們收集電子郵件和手機號碼是為了了解協議的原因和諮詢。 當收集和使用個人信息的目的實現時，收集的個人信息將被立即銷毀，除非有必要通過相關法律或公司內部政策予以保護。 \n有關詳細信息，請參閱\n隱私政策\n。'
      ,'同意した内容の原因を特定および円滑な相談をするために、電子メール、携帯電話の番号を収集します。収集された個人情報は、個人情報の収集及び利用目的が達成されると、関連する法令や社内方針によって保存する必要が場合を除いて、遅滞なく破棄します。\n詳細については、\n個人情報の処理方針\nを参照してください。'],
      REVIE49:['위 내용에 동의합니다.','I agree to the above.','我同意上述內容。','上記の内容に同意します。'],
      REVIE50:['문의하신내용','Your inquiry','你的詢問','お問い合わせいただいた内容'],
      REVIE51:['답변내용','Answer content','回答內容','回答内容'],
      REVIE52:['고객센터/도움말','Customer Center / Help','客戶中心/幫助','お客様センター/ヘルプ'],
      REVIE53:['고객센터 전화걸기','Call a customer center','致電客戶中心','お客様センター電話をかける'],
      REVIE54:['공지사항','Notice','通知','お知らせ'],
      REVIE55:['개인정보처리방침','Privacy Policy','隱私政策','個人情報の処理方針'],
      REVIE56:['회사정보','Company Information','公司信息','会社情報'],
      REVIE57:['상호','Mutual','相互','相互'],
      REVIE58:['대표','CEO','表示','代表'],
      REVIE59:['주소','Address','地址','アドレス'],
      REVIE60:['사업자등록번호','Company Registration Number','商業登記號碼','事業者登録番号'],
      REVIE61:['새로운 비밀번호가 발송됩니다.','A new password will be sent.','將發送新密碼。','新しいパスワードが送信されます。'],
      REVIE62:['메일발송','Send mail','發送郵件','メールを送信'],
      REVIE63:['알람설정','Alarm setting','報警設置','アラーム設定'],
      REVIE64:['Push 알림','Push notifications','推送通知','Push通知'],
      REVIE65:['마케팅 알림','Marketing alerts','營銷提醒','マーケティング通知'],
      REVIE66:['방해금지 시간대 설정','Disruption time zone setting','中斷時區設置','妨害禁止時間帯の設定'],
      REVIE67:['사용안함','not used','殘','を無効にする'],
      REVIE68:['해당시간에 알림을 받지 않습니다.','You will not be notified at that time.','您當時不會收到通知。','その時間に通知を受けません。'],
      REVIE69:['시작시간','Start time','開始時間','開始時間'],
      REVIE70:['종료시간','End time','結束時間','終了時間'],
      REVIE71:['상세내역','details','詳細信息','詳細'],
      REVIE72:['값을 모두 입력해주세요','Please enter all values','請輸入所有值','値をすべて入力してください'],
      REVIE73:['개인정보 처리방침을 동의해주세요','Please accept my privacy policy','請接受我的隱私政策','個人情報の処理方針に同意してください'],
      REVIE75:['문의하신 내역이 없습니다.','There is no history of inquiry.','沒有調查的歷史。','お問い合わせいただいた内容がありません。'],
      REVIE74:['설정 저장완료','Settings saved','設置已保存','設定を保存完了'],
      REVIE76:['설정 저장실패','Failed to save settings','無法保存設置','設定の保存に失敗'],
      REVIE77:['오류가 발생하였습니다.잠시후 다시시도해주세요.','An error has occurred. Please try again later.','發生錯誤，請稍後再試。','エラーが発生しました。しばらくしてから再度試してください。'],
      REVIE78:['출금계좌 변경완료','Completion of withdrawal account change','完成取款帳戶更改','出金口座変更完了'],
      REVIE79:['접수가 되었습니다.','It is accepted.','它被接受了。','受付がされた。'],
      REVIE80:['접수에 실패하였습니다.','The reception failed.','接待失敗了。','受付に失敗しました。'],
      REVIE81:['이용약관','Terms of service','條款和條件','利用規約'],
      REVIE82:['2차 비밀번호를 한번더 입력해주세요','Please enter your 2nd password again','請再次輸入您的第二個密碼','2次パスワードをもう一度入力してください'],
      REVIE83:['주소 등록','Address registration','地址註冊','アドレス登録'],
      REVIE84:['주소 수정','Edit address','編輯地址','アドレスの変更'],
      REVIE85:['지갑설정','Wallet settings','錢包設置','財布の設定'],
      REVIE86:['추천인을 입력하세요','Please enter your referrer','請輸入您的推薦人','オススメを入力し'],
      REVIE87:['후원인을 입력하세요','Please enter a sponsor','請輸入贊助商','フウォンインを入力してください'],
      REVIE88:['후원인이 이미 가득 찼습니다.','The sponsor is already full.','贊助商已經滿員了。','フウォンインが既にいっぱいです。'],
      REVIE89:['추천인','Recommender','導購','オススメ'],
      REVIE90:['후원인','Sponsor','支持者','スポンサーである'],
      REVIE91:['2차비밀번호를 설정 하셔야 합니다.','You need to set a secondary password.','您需要設置二級密碼。','2次パスワードを設定する必要があります。'],
      REVIE92:['설정','Confirm','確認','Thiết lập'],
      REVIE93:['설정','Confirm','確認','Thiết lập'],
      WALLET_LANG10: ["출금", "Withdraw", "提款","Rút tiền"],
      WALLET_LANG11: ["입금", "deposit", "存款","Gửi tiền"],
      CHMYINFO1: ["기본정보 변경","Change basic information","更改基本信息","Thay đổi thông tin cơ bản"],
      LEFTMENU6: ["언어변경","Change language","改变语言","Thay đổi ngôn ngữ"],
      BASICINF14: ["설정 저장 완료","Settings saved","设置已保存","Lưu thiết lập hoàn tất"],
    };

    if (typeof module == 'object') {

      module.exports = lang;
    }
